## YAML Template.
---

scheduler:
    pool-size: 3
    traditional:
        delay:
            initial: 5000
            fixed: 60000

server:
    port: 8080
    ssl:
        key-store: classpath:starturn-https.jks
        key-store-password: Password@1
        key-store-type: JKS
        key-alias: starturn-https
        key-password: Password@1

# File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file:
    upload-dir: /starturn/uploads
    profile-pic-dir: /starturn/pictures
    
token:
    validity: 2
    secret-key: Pa$$007##
