package com.starturn.engine.database.entities;
// Generated 01-Mar-2020 08:29:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Bank generated by hbm2java
 */
@Entity
@Table(name="BANK"
    ,catalog="starturn"
)
public class Bank  implements java.io.Serializable {


     private int id;
     private Long version;
     private String name;
     private String sortCode;
     private Set<MemberProfile> memberProfiles = new HashSet<MemberProfile>(0);

    public Bank() {
    }

	
    public Bank(int id) {
        this.id = id;
    }
    public Bank(int id, String name, String sortCode, Set<MemberProfile> memberProfiles) {
       this.id = id;
       this.name = name;
       this.sortCode = sortCode;
       this.memberProfiles = memberProfiles;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

    
    @Column(name="name", length=500)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="sort_code", length=50)
    public String getSortCode() {
        return this.sortCode;
    }
    
    public void setSortCode(String sortCode) {
        this.sortCode = sortCode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bank")
    public Set<MemberProfile> getMemberProfiles() {
        return this.memberProfiles;
    }
    
    public void setMemberProfiles(Set<MemberProfile> memberProfiles) {
        this.memberProfiles = memberProfiles;
    }




}


