package com.starturn.engine.database.entities;
// Generated 01-Mar-2020 08:29:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * ContributionFrequency generated by hbm2java
 */
@Entity
@Table(name="CONTRIBUTION_FREQUENCY"
    ,catalog="starturn"
)
public class ContributionFrequency  implements java.io.Serializable {


     private Integer id;
     private Long version;
     private String name;
     private Set<TargetSavingsPlan> targetSavingsPlans = new HashSet<TargetSavingsPlan>(0);
     private Set<EsusuGroup> esusuGroups = new HashSet<EsusuGroup>(0);

    public ContributionFrequency() {
    }

    public ContributionFrequency(String name, Set<TargetSavingsPlan> targetSavingsPlans, Set<EsusuGroup> esusuGroups) {
       this.name = name;
       this.targetSavingsPlans = targetSavingsPlans;
       this.esusuGroups = esusuGroups;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

    
    @Column(name="name", length=500)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contributionFrequency")
    public Set<TargetSavingsPlan> getTargetSavingsPlans() {
        return this.targetSavingsPlans;
    }
    
    public void setTargetSavingsPlans(Set<TargetSavingsPlan> targetSavingsPlans) {
        this.targetSavingsPlans = targetSavingsPlans;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contributionFrequency")
    public Set<EsusuGroup> getEsusuGroups() {
        return this.esusuGroups;
    }
    
    public void setEsusuGroups(Set<EsusuGroup> esusuGroups) {
        this.esusuGroups = esusuGroups;
    }




}


