package com.starturn.engine.database.entities;
// Generated 01-Mar-2020 08:29:01 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * EnvironmentalProperty generated by hbm2java
 */
@Entity
@Table(name="ENVIRONMENTAL_PROPERTY"
    ,catalog="starturn"
)
public class EnvironmentalProperty  implements java.io.Serializable {


     private int id;
     private Long version;
     private String propertyName;
     private String propertyValue;

    public EnvironmentalProperty() {
    }

	
    public EnvironmentalProperty(int id) {
        this.id = id;
    }
    public EnvironmentalProperty(int id, String propertyName, String propertyValue) {
       this.id = id;
       this.propertyName = propertyName;
       this.propertyValue = propertyValue;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

    
    @Column(name="property_name", length=100)
    public String getPropertyName() {
        return this.propertyName;
    }
    
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }

    
    @Column(name="property_value", length=100)
    public String getPropertyValue() {
        return this.propertyValue;
    }
    
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue;
    }




}


