package com.starturn.engine.database.entities;
// Generated 01-Mar-2020 08:29:01 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * EsusuGroupInvites generated by hbm2java
 */
@Entity
@Table(name="ESUSU_GROUP_INVITES"
    ,catalog="starturn"
)
public class EsusuGroupInvites  implements java.io.Serializable {


     private Integer id;
     private Long version;
     private EsusuGroup esusuGroup;
     private MemberProfile memberProfile;
     private Boolean accepted;
     private Boolean rejected;
     private Date responseDate;
     private Date invitedDate;
     private String invitedByUsername;
     private Boolean treated;

    public EsusuGroupInvites() {
    }

    public EsusuGroupInvites(EsusuGroup esusuGroup, MemberProfile memberProfile, Boolean accepted, Boolean rejected, Date responseDate, Date invitedDate, String invitedByUsername,Boolean treated) {
       this.esusuGroup = esusuGroup;
       this.memberProfile = memberProfile;
       this.accepted = accepted;
       this.rejected = rejected;
       this.responseDate = responseDate;
       this.invitedDate = invitedDate;
       this.invitedByUsername = invitedByUsername;
       this.treated = treated;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="esusu_group_id")
    public EsusuGroup getEsusuGroup() {
        return this.esusuGroup;
    }
    
    public void setEsusuGroup(EsusuGroup esusuGroup) {
        this.esusuGroup = esusuGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="member_profile_id")
    public MemberProfile getMemberProfile() {
        return this.memberProfile;
    }
    
    public void setMemberProfile(MemberProfile memberProfile) {
        this.memberProfile = memberProfile;
    }

    
    @Column(name="accepted")
    public Boolean getAccepted() {
        return this.accepted;
    }
    
    public void setAccepted(Boolean accepted) {
        this.accepted = accepted;
    }

    
    @Column(name="rejected")
    public Boolean getRejected() {
        return this.rejected;
    }
    
    public void setRejected(Boolean rejected) {
        this.rejected = rejected;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="response_date", length=10)
    public Date getResponseDate() {
        return this.responseDate;
    }
    
    public void setResponseDate(Date responseDate) {
        this.responseDate = responseDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="invited_date", length=10)
    public Date getInvitedDate() {
        return this.invitedDate;
    }
    
    public void setInvitedDate(Date invitedDate) {
        this.invitedDate = invitedDate;
    }

    
    @Column(name="invited_by_username", length=50)
    public String getInvitedByUsername() {
        return this.invitedByUsername;
    }
    
    public void setInvitedByUsername(String invitedByUsername) {
        this.invitedByUsername = invitedByUsername;
    }

    @Column(name="treated")
    public Boolean getTreated() {
        return treated;
    }

    public void setTreated(Boolean treated) {
        this.treated = treated;
    }




}


