package com.starturn.engine.database.entities;
// Generated 01-Mar-2020 08:29:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * EsusuGroupMembers generated by hbm2java
 */
@Entity
@Table(name="ESUSU_GROUP_MEMBERS"
    ,catalog="starturn"
)
public class EsusuGroupMembers  implements java.io.Serializable {


     private Integer id;
     private Long version;
     private EsusuGroup esusuGroup;
     private MemberProfile memberProfile;
     private String collectionPosition;
     private BigDecimal expectedAmount;
     private BigDecimal amountPaid;
     private Boolean paid;
     private Date paidDate;
     private Date creationDate;
     private Date expectedCollectionDate;
     private String createdByUsername;

    public EsusuGroupMembers() {
    }

    public EsusuGroupMembers(EsusuGroup esusuGroup, MemberProfile memberProfile, String collectionPosition, BigDecimal expectedAmount, BigDecimal amountPaid, Boolean paid, Date paidDate, Date creationDate, Date expectedCollectionDate, String createdByUsername) {
       this.esusuGroup = esusuGroup;
       this.memberProfile = memberProfile;
       this.collectionPosition = collectionPosition;
       this.expectedAmount = expectedAmount;
       this.amountPaid = amountPaid;
       this.paid = paid;
       this.paidDate = paidDate;
       this.creationDate = creationDate;
       this.expectedCollectionDate = expectedCollectionDate;
       this.createdByUsername = createdByUsername;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="esusu_group_id")
    public EsusuGroup getEsusuGroup() {
        return this.esusuGroup;
    }
    
    public void setEsusuGroup(EsusuGroup esusuGroup) {
        this.esusuGroup = esusuGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="member_profile_id")
    public MemberProfile getMemberProfile() {
        return this.memberProfile;
    }
    
    public void setMemberProfile(MemberProfile memberProfile) {
        this.memberProfile = memberProfile;
    }

    
    @Column(name="collection_position", length=50)
    public String getCollectionPosition() {
        return this.collectionPosition;
    }
    
    public void setCollectionPosition(String collectionPosition) {
        this.collectionPosition = collectionPosition;
    }

    
    @Column(name="expected_amount", scale=4)
    public BigDecimal getExpectedAmount() {
        return this.expectedAmount;
    }
    
    public void setExpectedAmount(BigDecimal expectedAmount) {
        this.expectedAmount = expectedAmount;
    }

    
    @Column(name="amount_paid", scale=4)
    public BigDecimal getAmountPaid() {
        return this.amountPaid;
    }
    
    public void setAmountPaid(BigDecimal amountPaid) {
        this.amountPaid = amountPaid;
    }

    
    @Column(name="paid")
    public Boolean getPaid() {
        return this.paid;
    }
    
    public void setPaid(Boolean paid) {
        this.paid = paid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="paid_date", length=10)
    public Date getPaidDate() {
        return this.paidDate;
    }
    
    public void setPaidDate(Date paidDate) {
        this.paidDate = paidDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="creation_date", length=10)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="expected_collection_date", length=10)
    public Date getExpectedCollectionDate() {
        return this.expectedCollectionDate;
    }
    
    public void setExpectedCollectionDate(Date expectedCollectionDate) {
        this.expectedCollectionDate = expectedCollectionDate;
    }

    
    @Column(name="created_by_username", length=50)
    public String getCreatedByUsername() {
        return this.createdByUsername;
    }
    
    public void setCreatedByUsername(String createdByUsername) {
        this.createdByUsername = createdByUsername;
    }




}


