package com.starturn.engine.database.entities;
// Generated 01-Mar-2020 08:29:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * MemberWalletTransaction generated by hbm2java
 */
@Entity
@Table(name="MEMBER_WALLET_TRANSACTION"
    ,catalog="starturn"
)
public class MemberWalletTransaction  implements java.io.Serializable {


     private int id;
     private Long version;
     private MemberProfile memberProfile;
     private TransactionType transactionType;
     private BigDecimal amount;
     private Date transactionDate;
     private Boolean isAutoDebit;

    public MemberWalletTransaction() {
    }

	
    public MemberWalletTransaction(int id) {
        this.id = id;
    }
    public MemberWalletTransaction(int id, MemberProfile memberProfile, TransactionType transactionType, BigDecimal amount, Date transactionDate, Boolean isAutoDebit) {
       this.id = id;
       this.memberProfile = memberProfile;
       this.transactionType = transactionType;
       this.amount = amount;
       this.transactionDate = transactionDate;
       this.isAutoDebit = isAutoDebit;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="member_profile_id")
    public MemberProfile getMemberProfile() {
        return this.memberProfile;
    }
    
    public void setMemberProfile(MemberProfile memberProfile) {
        this.memberProfile = memberProfile;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="transaction_type_id")
    public TransactionType getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }

    
    @Column(name="amount", scale=4)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="transaction_date", length=10)
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="is_auto_debit")
    public Boolean getIsAutoDebit() {
        return this.isAutoDebit;
    }
    
    public void setIsAutoDebit(Boolean isAutoDebit) {
        this.isAutoDebit = isAutoDebit;
    }




}


