package com.starturn.engine.database.entities;
// Generated 01-Mar-2020 08:29:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * RequirementGroup generated by hbm2java
 */
@Entity
@Table(name="REQUIREMENT_GROUP"
    ,catalog="starturn"
)
public class RequirementGroup  implements java.io.Serializable {


     private int id;
     private Long version;
     private String groupName;
     private Set<RequirementGroupAccess> requirementGroupAccesses = new HashSet<RequirementGroupAccess>(0);

    public RequirementGroup() {
    }

	
    public RequirementGroup(int id) {
        this.id = id;
    }
    public RequirementGroup(int id, String groupName, Set<RequirementGroupAccess> requirementGroupAccesses) {
       this.id = id;
       this.groupName = groupName;
       this.requirementGroupAccesses = requirementGroupAccesses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

    
    @Column(name="group_name", length=100)
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="requirementGroup")
    public Set<RequirementGroupAccess> getRequirementGroupAccesses() {
        return this.requirementGroupAccesses;
    }
    
    public void setRequirementGroupAccesses(Set<RequirementGroupAccess> requirementGroupAccesses) {
        this.requirementGroupAccesses = requirementGroupAccesses;
    }




}


