package com.starturn.engine.database.entities;
// Generated 01-Mar-2020 08:29:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * TargetSavings generated by hbm2java
 */
@Entity
@Table(name="TARGET_SAVINGS"
    ,catalog="starturn"
)
public class TargetSavings  implements java.io.Serializable {


     private Integer id;
     private Long version;
     private MemberProfile memberProfile;
     private TargetSavingsPlan targetSavingsPlan;
     private BigDecimal targetAmount;
     private BigDecimal periodicAmount;
     private Date applicationDate;
     private Date startDate;
     private Date endDate;
     private Boolean savingsWithdrawn;
     private BigDecimal amountWithdrawn;
     private BigDecimal interestAmount;
     private BigDecimal totalAmountWithdrawn;
     private Date withdrawalDate;
     private Boolean lockedSavings;
     private BigDecimal interestRate;
     private Set<Transaction> transactions = new HashSet<Transaction>(0);

    public TargetSavings() {
    }

    public TargetSavings(MemberProfile memberProfile, TargetSavingsPlan targetSavingsPlan, BigDecimal targetAmount, BigDecimal periodicAmount, Date applicationDate, Date startDate, Date endDate, Boolean savingsWithdrawn, BigDecimal amountWithdrawn, BigDecimal interestAmount, BigDecimal totalAmountWithdrawn, Date withdrawalDate, Boolean lockedSavings, BigDecimal interestRate, Set<Transaction> transactions) {
       this.memberProfile = memberProfile;
       this.targetSavingsPlan = targetSavingsPlan;
       this.targetAmount = targetAmount;
       this.periodicAmount = periodicAmount;
       this.applicationDate = applicationDate;
       this.startDate = startDate;
       this.endDate = endDate;
       this.savingsWithdrawn = savingsWithdrawn;
       this.amountWithdrawn = amountWithdrawn;
       this.interestAmount = interestAmount;
       this.totalAmountWithdrawn = totalAmountWithdrawn;
       this.withdrawalDate = withdrawalDate;
       this.lockedSavings = lockedSavings;
       this.interestRate = interestRate;
       this.transactions = transactions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="member_profile_id")
    public MemberProfile getMemberProfile() {
        return this.memberProfile;
    }
    
    public void setMemberProfile(MemberProfile memberProfile) {
        this.memberProfile = memberProfile;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="target_savings_plan_id")
    public TargetSavingsPlan getTargetSavingsPlan() {
        return this.targetSavingsPlan;
    }
    
    public void setTargetSavingsPlan(TargetSavingsPlan targetSavingsPlan) {
        this.targetSavingsPlan = targetSavingsPlan;
    }

    
    @Column(name="target_amount", scale=4)
    public BigDecimal getTargetAmount() {
        return this.targetAmount;
    }
    
    public void setTargetAmount(BigDecimal targetAmount) {
        this.targetAmount = targetAmount;
    }

    
    @Column(name="periodic_amount", scale=4)
    public BigDecimal getPeriodicAmount() {
        return this.periodicAmount;
    }
    
    public void setPeriodicAmount(BigDecimal periodicAmount) {
        this.periodicAmount = periodicAmount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="application_date", length=10)
    public Date getApplicationDate() {
        return this.applicationDate;
    }
    
    public void setApplicationDate(Date applicationDate) {
        this.applicationDate = applicationDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start_date", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="end_date", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="savings_withdrawn")
    public Boolean getSavingsWithdrawn() {
        return this.savingsWithdrawn;
    }
    
    public void setSavingsWithdrawn(Boolean savingsWithdrawn) {
        this.savingsWithdrawn = savingsWithdrawn;
    }

    
    @Column(name="amount_withdrawn", scale=4)
    public BigDecimal getAmountWithdrawn() {
        return this.amountWithdrawn;
    }
    
    public void setAmountWithdrawn(BigDecimal amountWithdrawn) {
        this.amountWithdrawn = amountWithdrawn;
    }

    
    @Column(name="interest_amount", scale=4)
    public BigDecimal getInterestAmount() {
        return this.interestAmount;
    }
    
    public void setInterestAmount(BigDecimal interestAmount) {
        this.interestAmount = interestAmount;
    }

    
    @Column(name="total_amount_withdrawn", scale=4)
    public BigDecimal getTotalAmountWithdrawn() {
        return this.totalAmountWithdrawn;
    }
    
    public void setTotalAmountWithdrawn(BigDecimal totalAmountWithdrawn) {
        this.totalAmountWithdrawn = totalAmountWithdrawn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="withdrawal_date", length=10)
    public Date getWithdrawalDate() {
        return this.withdrawalDate;
    }
    
    public void setWithdrawalDate(Date withdrawalDate) {
        this.withdrawalDate = withdrawalDate;
    }

    
    @Column(name="locked_savings")
    public Boolean getLockedSavings() {
        return this.lockedSavings;
    }
    
    public void setLockedSavings(Boolean lockedSavings) {
        this.lockedSavings = lockedSavings;
    }

    
    @Column(name="interest_rate", scale=4)
    public BigDecimal getInterestRate() {
        return this.interestRate;
    }
    
    public void setInterestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="targetSavings")
    public Set<Transaction> getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set<Transaction> transactions) {
        this.transactions = transactions;
    }




}


