package com.starturn.engine.database.entities;
// Generated 01-Mar-2020 08:29:01 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * UserToken generated by hbm2java
 */
@Entity
@Table(name="USER_TOKEN"
    ,catalog="starturn"
)
public class UserToken  implements java.io.Serializable {


     private Integer id;
     private Long version;
     private MemberProfile memberProfile;
     private String username;
     private String token;
     private Date dateCreated;
     private Date dateValidated;
     private Boolean validated;
     private Boolean expired;

    public UserToken() {
    }

    public UserToken(MemberProfile memberProfile, String username, String token, Date dateCreated, Date dateValidated, Boolean validated, Boolean expired) {
       this.memberProfile = memberProfile;
       this.username = username;
       this.token = token;
       this.dateCreated = dateCreated;
       this.dateValidated = dateValidated;
       this.validated = validated;
       this.expired = expired;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Version
    @Column(name="version")
    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="member_profile_id")
    public MemberProfile getMemberProfile() {
        return this.memberProfile;
    }
    
    public void setMemberProfile(MemberProfile memberProfile) {
        this.memberProfile = memberProfile;
    }

    
    @Column(name="username", length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="token", length=50)
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_validated", length=19)
    public Date getDateValidated() {
        return this.dateValidated;
    }
    
    public void setDateValidated(Date dateValidated) {
        this.dateValidated = dateValidated;
    }

    
    @Column(name="validated")
    public Boolean getValidated() {
        return this.validated;
    }
    
    public void setValidated(Boolean validated) {
        this.validated = validated;
    }

    
    @Column(name="expired")
    public Boolean getExpired() {
        return this.expired;
    }
    
    public void setExpired(Boolean expired) {
        this.expired = expired;
    }




}


